### ISSUE TITLE
0.98报错 @DaTa['message']缺失

### ISSUE THREAD

**Issue by Damon-Shen** [xcray/xiaomi_aqara-button-simulation-on-hass#1]
在0.98里，报错@data['message']缺失，然后没法使用了

**Comment by xcray** [comment]
我几乎每次有新版本都会更新，没碰到过这个报错，不清楚为啥。
不过从0.99开始，ha的代码有变化，所以我也跟着改了。

**Comment by Damon-Shen** [comment]
升级到了0.99，用服务的方式去模拟click，没有反应，也看不到任何报错信息，看了源码，gateway.write_to_hub(device_id, status=simu_status)，是通过这个去发送的，但是不知道为什么就是不成功，网关也是v3的

**Comment by xcray** [comment]
你之前用这个成功过吗？我的意思是先排除一下版本问题。
其次，你是在自动化当中用的还是在开发者工具那儿手工执行的？
不管在哪儿，消息体的格式必须正确、内容也必须正确（mac地址、did、状态）

**Comment by Damon-Shen** [comment]
之前也没成功过，在开发者工具-服务那里操作的
环境是群晖+docker，格消息格式正确，内容也对应到了网关和实体id，现在是用最新的0.99.3版本

**Comment by Damon-Shen** [comment]
格式是正确的，这个call service后，日志内无任何报错，在米家app内也没看到有click事件，关联的自动化也未执行，我用的是圆形的小米按钮
{
  "gw_mac": "7811DCF79E69",
  "device_id": "158d00024e9a7b",
  "status": "click"
}

**Comment by xcray** [comment]
不知道你具体修改的步骤，怀疑你修改代码不够彻底。说下我的，供参考。
注：我对docker不怎么了解。不过我也是在群晖docker上跑的HA。
1. 下载镜像后先不创建容器，而是先修改镜像代码，步骤如下。
2. ssh群晖后，先sudo -i，然后转到路径/volume1/\@docker/btrfs/subvolumes/
3. 利用du|grep xiaomi_aqara找出目标路径。
在0.98版本之前创建容器前只有一个子目录，但后来这个操作可以找出3个子目录（另外两个pycache的不用管），不懂为啥这样。
4. 分别进入3个子目录下的usr/src/homeassistant/homeassistant/components/xiaomi_aqara/，分别替换其中的3个文件，就是__init__.py、sensor.py、services.yaml。（也许只需要替换一个子目录，但我懒得试了，索性3个子目录都替换）
5. 然后按照正常步骤创建容器。

今天刚刚升级0.100.1，ha官方代码又有点小的改动（3行），所以我的代码也跟着改了，使用正常。

**Comment by xcray** [comment]
后来学会了一个更简便的替换方法：
把3个文件放在准备给容器用作config的目录下，然后在容器里开一个bash终端进行操作，然后重启即可。
